services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=chauthi
      - MONGO_INITDB_ROOT_PASSWORD=chauthi
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=chauthi
      - ME_CONFIG_MONGODB_ADMINPASSWORD=chauthi
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://chauthi:chauthi@mongodb:27017/
      - ME_CONFIG_BASICAUTH=false
volumes:
  mongo: {}